# Generated by Django 4.2.3 on 2023-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_image_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="labels",
            field=models.TextField(blank=True, null=True),
        ),
    ]
