# Generated by Django 4.2.3 on 2023-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_image_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="image",
            name="labels",
        ),
        migrations.AddField(
            model_name="image",
            name="labels",
            field=models.ManyToManyField(to="main.label"),
        ),
    ]
